#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
#provide_public=$3
#provide_shared=$4

#install fastcgiwrap
sudo apt-get update
sudo apt-get install -y fcgiwrap

sudo yunohost app checkurl $domain$path -a git-repositories
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

path_public=$path/public
path_shared=$path/shared

final_path=/var/www/git-repositories
final_path_public=/var/www/git-repositories/public
final_path_shared=/var/www/git-repositories/shared

sudo mkdir -p $final_path
sudo mkdir -p $final_path_public
sudo mkdir -p $final_path_shared

git_users=$(ldapsearch -h localhost -b ou=users,dc=yunohost,dc=org -x objectClass=mailAccount uid | grep uid: | sed 's/uid: //' | xargs)
for myuser in $freshrss_users
do
	#TODO : need to create private path
done

# Modify Nginx configuration file and copy it to Nginx conf directory
# sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
# sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf

sed -i "s@PATHTOCHANGE@$path_public@g" ../conf/nginx-public.conf
sed -i "s@ALIASTOCHANGE@$final_path_public/@g" ../conf/nginx-public.conf

sed -i "s@PATHTOCHANGE@$path_shared@g" ../conf/nginx-shared.conf
sed -i "s@ALIASTOCHANGE@$final_path_shared/@g" ../conf/nginx-shared.conf

sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/git-repositories.conf
sudo cp ../conf/nginx-public.conf /etc/nginx/conf.d/$domain.d/git-repositories-public.conf
sudo cp ../conf/nginx-shared.conf /etc/nginx/conf.d/$domain.d/git-repositories-shared.conf


#skip public diriectory
sudo yunohost app setting git-repositories skipped_uris -v /public/

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf